### ISSUE TITLE
not compatible with macOS Metal Backend

### ISSUE THREAD

**Issue by cekuhnen** [kevancress/MeasureIt-ARCH#267] opened 2023-11-06 17:14 UTC
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/ez5554/Library/Application Support/Blender/3.6/scripts/addons/MeasureIt_ARCH-development/__init__.py", line 78, in <module>
    from . import measureit_arch_main
  File "/Users/ez5554/Library/Application Support/Blender/3.6/scripts/addons/MeasureIt_ARCH-development/measureit_arch_main.py", line 34, in <module>
    from .measureit_arch_geometry import clear_batches, update_text, draw3d_loop, preview_dual, check_obj_vis
  File "/Users/ez5554/Library/Application Support/Blender/3.6/scripts/addons/MeasureIt_ARCH-development/measureit_arch_geometry.py", line 100, in <module>
    triShader = gpu.types.GPUShader(
Exception: Shader Compile Error, see console for more details

**Comment by kevancress** [comment] 2023-12-17 17:31
Duplicate of https://github.com/kevancress/MeasureIt_ARCH/issues/263

**Closed as completed by kevancress** 2023-12-17 17:31 UTC
