### ISSUE TITLE
Can't activate addon in Blender 4.0.1

### ISSUE THREAD

**Issue by FelixHob** [kevancress/MeasureIt-ARCH#271] opened 2024-02-19 12:57 UTC
<img width="496" alt="image" src="https://github.com/kevancress/MeasureIt_ARCH/assets/160487766/a6890bf5-fe9f-4e08-9182-d74265273c7c">

**Comment by kevancress** [comment] 2024-02-22 18:36
Hey @FelixHob,

Which version of the addon are you using? If you download the zip directly from the main github page it should work fine with blender 4.0+.

From the error message this looks like you're trying to install the v0.4 release, which wont work with current versions of blender.

**Comment by kevancress** [comment] 2024-02-28 22:54
@FelixHob 
Closing this for now since I can't reproduce the issue. If your still not able to activate the latest version of the addon with Blender 4.0 feel free to open another issue.

**Closed as completed by kevancress** 2024-02-28 22:54 UTC
