### ISSUE TITLE
Preview problem in Blender 4.02

### ISSUE THREAD

**Issue by ajo-maker** [kevancress/MeasureIt-ARCH#275] opened 2024-03-25 00:58 UTC
Hi Kevan,
What a great add-on! Thank you for this.
I updated blender to version 4.02. And now I have problems with the line and dimension preview in the 3D viewport. Do you have any idea how I can fix this?
![LinePreview3 62](https://github.com/kevancress/MeasureIt_ARCH/assets/58310986/927eb3ba-107f-4d0b-9840-e7e125617d32)
![LinePreview4 02](https://github.com/kevancress/MeasureIt_ARCH/assets/58310986/0a444eaf-ec80-48cc-bc6a-c6708242af02)
AJ

**Comment by kevancress** [comment] 2024-04-23 15:42
@ajo-maker 

The line weight differences were an intentional change to bring the raster and vector line weights into alignment. Not sure why the dashed lines aren't showing up. is the the latest development version of the addon, what system and graphics card are you using?

**Comment by ajo-maker** [comment] 2024-04-28 13:01
AMD Ryzen 9 5900HX with Radeon Graphics           3.30 GHz
nvidia geforce rtx 3070 laptop gpu

The dashed lines are indeed not displayed.
But the different line thicknesses are also not visible in Blender. In fact, everything is displayed on one line thickness. The specified thickness will only be visible in the generated SVG file.

**Comment by kevancress** [comment] 2024-04-28 16:50
Ahh okay, yep seeing that more clearly now in your image. Can you post the demo file that was used to generate that preview image? I'm not able to reproduce this on my end, and we're working with the same graphics card, so I'm not quite sure what could be causing the difference in preview. Here's how things are looking on my end. [Belnder 4.2]

![image](https://github.com/kevancress/MeasureIt_ARCH/assets/16860574/192abb47-0fe1-4b30-9378-25d3f3c9e082)

Can you also confirm the addon version info at the bottom of the settings in the scene panel. the latest version should look like this:

![image](https://github.com/kevancress/MeasureIt_ARCH/assets/16860574/5abb7347-fa0e-47f2-bd8e-1aad017c2c40)

**Comment by ajo-maker** [comment] 2024-04-28 22:39
The version was the problem. I installed the latest version and it works perfectly now!
Thanks!
![image](https://github.com/kevancress/MeasureIt_ARCH/assets/58310986/f6239248-96f4-45fa-9be3-158f0570d6ec)

**Comment by kevancress** [comment] 2024-04-29 14:40
Ahh okay, yeah last December was right around when I was updating the drawing system, so it was only half working then.

Glad its working now! Going to close this issue, but let me know if you find any other bugs!

**Closed as completed by kevancress** 2024-04-29 14:40 UTC
