### ISSUE TITLE
Measurements "blacked out" on opening file

### ISSUE THREAD

**Issue by Blenderbugg** [kevancress/MeasureIt-ARCH#7] opened 2019-03-26 22:13 UTC
Opened my file, measurements appearing as black blocks. Click on colour tab in Dimensions box, numbers return.
<img width="1454" alt="Screen Shot 2019-03-27 at 6 19 07 am" src="https://user-images.githubusercontent.com/28837471/55027211-d7d64a00-5058-11e9-8d38-542f9fd79ce5.png">
<img width="1331" alt="Screen Shot 2019-03-27 at 6 19 32 am" src="https://user-images.githubusercontent.com/28837471/55027212-d7d64a00-5058-11e9-9955-7fc251692f41.png">

**Comment by kevancress** [comment] 2019-03-26 22:33
I've been able to reproduce this one on windows too with files with large numbers of dimensions. Strange that all the dimensions are returning the same value when the text comes back.  For me they come back to their correct values if the geometry is modified, is that the case for you?

It looks like the method I'm using to draw text has some hiccups. I'm having to work around some strange behavior of the text api in python in 2.8 might have to do some digging in the source to find a full fix to this one.

**Comment by Blenderbugg** [comment] 2019-03-26 23:24
I have made a little video and put it up on a workspace I have for this sort of thing.....

https://youtu.be/k6t2MUdWzzM

**Comment by kevancress** [comment] 2019-03-27 05:14
Wow! This one was a fun one, thanks for the video, that really got me on the right track to get this sorted out. Turns out the memory locations that I was assigning to store the text for the dimensions could get randomly reassigned when reloading the file and would overlap with each other, and occasionally with memory locations storing bits of the user interface.

Should be all fixed in the last commit, it seems to be working on my end at least, let me know if it fixed the problem for you too

**Closed** 2019-03-28 20:32 UTC
