### ISSUE TITLE
MeasureIT_ARCH Views no longer sets View Layer

### ISSUE THREAD

**Issue by baldyman01** [kevancress/MeasureIt-ARCH#287] opened 2024-09-30 11:31 UTC
Selecting a View in the MeasureIT_ARCH views menu does not switch View Layer on Blender 4.2.2. 

4.2.0 still works as expected.

Cheers
Pete

**Comment by kevancress** [comment] 2024-10-04 16:03
hmm probably just a small api change between versions. I'll look into this today

**Comment by kevancress** [comment] 2024-10-04 16:20
@baldyman01

I'm not able to reproduce this in my files in Blender 4.2.2 LTS or the 4.3 Beta... Could you post an example file where this is happening?

Thanks!
Kev

**Comment by kevancress** [comment] 2024-10-04 16:23
Oh wait nevermind found it! it has to do with the render engine enum, if the view your switching to is set to Eevee then the view change fails because the engine name changed to eevee_next in the api, and my version checking code was only making the enum swap for version 4.2.0!

**Comment by kevancress** [comment] 2024-10-04 16:30
Okay should be fixed in 8960d1e9c2920114841102f49ce5a8fb3fa76a0f. Give it a try and let me know if it works for you!

**Comment by baldyman01** [comment] 2024-10-23 15:50
Yep, confirmed working on 4.2.3. 

Cheers!

**Closed as completed** 2024-11-01 15:37 UTC
Labels: :outbox_tray: Resolved. Pending Confirmation
